/**
 * Shared TypeScript types for Schnitzel.
 *
 * Document types are auto-generated by Payload CMS (`payload generate:types`)
 * and re-exported here so every app in the monorepo uses a single source of truth.
 *
 * To regenerate after a collection/field change:
 *   bun run generate:types   (from the repo root)
 */

// Re-export the auto-generated Payload document types
export type { Config, Episode, Media, Page, User } from "./payload-types";

// Re-export for CMS-internal typing if needed
export type { EpisodesSelect, MediaSelect, PagesSelect } from "./payload-types";

/**
 * Map from collection slug to its document type.
 * Used by the type-safe API client to infer return types.
 */
import type { Config } from "./payload-types";

/** Valid slugs for public-facing Payload collections. */
export type CollectionSlug = keyof Config["collections"];

/** Resolve a collection slug to its document type. */
export type CollectionDocument<S extends CollectionSlug> =
  Config["collections"][S];

/** Generic Payload REST API list response. */
export interface PayloadListResponse<T> {
  docs: T[];
  totalDocs: number;
  totalPages: number;
  page: number;
  limit: number;
  hasNextPage: boolean;
  hasPrevPage: boolean;
}

/**
 * Helper: extract the `Media` object from a possibly-unresolved relation field.
 * When `depth >= 1`, Payload expands upload relations to their full object.
 * When `depth = 0`, it returns the raw ID (number).
 */
import type { Media } from "./payload-types";

export function resolveMedia(
  field: number | null | undefined | Media
): Media | null {
  if (field != null && typeof field === "object") return field;
  return null;
}

/**
 * Build a CSS `object-position` value from a Media's focal point.
 * Defaults to "50% 50%" (center) when focal point fields are missing.
 */
export function focalPosition(media: Media | null | undefined): string {
  const x = media?.focalX ?? 50;
  const y = media?.focalY ?? 50;
  return `${x}% ${y}%`;
}
